package ReverseModule;


/**
* ReverseModule/Reverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Friday, 9 May, 2025 6:11:58 PM IST
*/

public interface Reverse extends ReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverse
